SP - fix for pr 2033
In pr2033, the official docker-composition was not working, because it
introduced a regression, making the Proxy bean unable to resolve the
public URL, following error arising:

org.springframework.beans.factory.BeanCreationException: Error creating
bean with name 'proxy' defined in ServletContext resource
[/WEB-INF/proxy-servlet.xml]: Invocation of init method failed; nested
exception is java.net.MalformedURLException: no protocol: ${publicUrl}

Tests: runtime in a docker compo.